In [1]:
import pandas as pd
import numpy as np

In [2]:
df_up = pd.read_csv('data/서울특별시 공공자전거 이용정보(월별)_25.1-6.csv')
df_up.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,202501,102,102. 망원역 1번출구 앞,일일권,NaN,20대,24,1510.39,15.41,66468.87,716
1,202501,102,102. 망원역 1번출구 앞,일일권,NaN,30대,22,1150.04,10.93,47128.28,649
2,202501,102,102. 망원역 1번출구 앞,일일권,NaN,40대,2,141.11,1.15,4946.15,33
3,202501,102,102. 망원역 1번출구 앞,일일권,NaN,50대,3,279.03,2.22,9584.22,80
4,202501,102,102. 망원역 1번출구 앞,일일권,NaN,기타,7,858.12,8.29,35708.33,304

In [4]:
df_up[['대여소번호', '대여소']] = df_up['대여소명'].str.extract(r'^(\d+)\.\s*(.*)$')
df_up['대여소번호'] = pd.to_numeric(
    df_up['대여소번호'],
    errors='coerce'
)

df_up['대여소'] = df_up['대여소'].str.strip()
df_up.rename(columns={'연령대코드': '연령대'}, inplace=True)

df_up = df_up.drop(['대여소명', '대여구분코드', '성별', '운동량', '탄소량'], axis=1)

In [5]:
df_up.head()

     대여일자  대여소번호  연령대  이용건수   이동거리(M)  이용시간(분)         대여소
0  202501  102.0  20대    24  66468.87      716  망원역 1번출구 앞
1  202501  102.0  30대    22  47128.28      649  망원역 1번출구 앞
2  202501  102.0  40대     2   4946.15       33  망원역 1번출구 앞
3  202501  102.0  50대     3   9584.22       80  망원역 1번출구 앞
4  202501  102.0   기타     7  35708.33      304  망원역 1번출구 앞

In [6]:
df_up['대여소번호'] = df_up['대여소번호'].astype('Int64')
df_up.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600437 entries, 0 to 600436
Data columns (total 7 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   대여일자     600437 non-null  int64
 1   대여소번호    600430 non-null  Int64
 2   연령대      600437 non-null  object
 3   이용건수     600437 non-null  int64
 4   이동거리(M)  600437 non-null  float64
 5   이용시간(분)  600437 non-null  int64
 6   대여소      600430 non-null  object
dtypes: Int64(1), float64(1), int64(3), object(2)
memory usage: 32.6+ MB

In [7]:
df_down = pd.read_csv('data/서울특별시 공공자전거 이용정보(월별)_25.7-12.csv')
df_down.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,202507,102,102. 망원역 1번출구 앞,일일권,NaN,20대,68,5353.58,51.93,224057.74,1849
1,202507,102,102. 망원역 1번출구 앞,일일권,NaN,30대,65,6345.95,54.21,233558.04,1773
2,202507,102,102. 망원역 1번출구 앞,일일권,NaN,40대,11,378.59,3.54,15314.12,122
3,202507,102,102. 망원역 1번출구 앞,일일권,NaN,50대,4,169.09,1.46,6287.07,100
4,202507,102,102. 망원역 1번출구 앞,일일권,NaN,60대,1,69.20,0.42,1820.25,9

In [9]:
df_down[['대여소번호', '대여소']] = df_down['대여소명'].str.extract(r'^(\d+)\.\s*(.*)$')
df_down['대여소번호'] = pd.to_numeric(
    df_down['대여소번호'],
    errors='coerce'
)

df_down['대여소'] = df_down['대여소'].str.strip()
df_down.rename(columns={'연령대코드': '연령대'}, inplace=True)

df_down = df_down.drop(['대여소명', '대여구분코드', '성별', '운동량', '탄소량'], axis=1)
df_down['대여소번호'] = df_down['대여소번호'].astype('Int64')

In [10]:
df_down.head()

     대여일자  대여소번호  연령대  이용건수    이동거리(M)  이용시간(분)         대여소
0  202507    102  20대    68  224057.74     1849  망원역 1번출구 앞
1  202507    102  30대    65  233558.04     1773  망원역 1번출구 앞
2  202507    102  40대    11   15314.12      122  망원역 1번출구 앞
3  202507    102  50대     4    6287.07      100  망원역 1번출구 앞
4  202507    102  60대     1    1820.25        9  망원역 1번출구 앞

In [11]:
df_up.shape

(600437, 7)

In [12]:
df_down.shape

(629975, 7)

In [13]:
df_up.to_csv('data/2025년_상반기_공공자전거_이용데이터_1-6.csv', index=False, encoding='utf-8-sig')
df_down.to_csv('data/2025년_하반기_공공자전거_이용데이터_7-12.csv', index=False, encoding='utf-8-sig')

print('데이터 출력 완료!')

데이터 출력 완료!

In [17]:
df_wd = pd.read_csv('data/OBS_ASOS_DD_20260820111027.csv')
df_wd

,지점,지점명,일시,평균기온(°C),일강수량(mm),평균 풍속(m/s),평균 상대습도(%),일 최심적설(cm)
0,108,서울,2025-01-01,2.6,NaN,2.2,64.3,NaN
1,108,서울,2025-01-02,0.5,NaN,2.1,48.8,NaN
2,108,서울,2025-01-03,-1.1,0.0,2.2,52.0,NaN
3,108,서울,2025-01-04,-0.1,NaN,1.7,49.6,NaN
4,108,서울,2025-01-05,1.2,6.7,2.5,85.0,6.4
5,108,서울,2025-01-06,1.0,3.0,2.8,75.6,3.9
6,108,서울,2025-01-07,-2.6,0.1,2.7,53.5,0.4
7,108,서울,2025-01-08,-3.4,0.0,2.7,55.1,0.2
8,108,서울,2025-01-09,-9.7,0.0,4.2,38.4,NaN
9,108,서울,2025-01-10,-7.3,NaN,1.6,48.0,NaN
10,108,서울,2025-01-11,-5.1,NaN,1.7,57.4,NaN
11,108,서울,2025-01-12,-3.4,NaN,1.8,59.9,NaN
12,108,서울,2025-01-13,-0.4,1.3,1.7,76.9,0.1
13,108,서울,2025-01-14,2.3,0.1,2.3,72.0,0.1
14,108,서울,2025-01-15,-3.5,NaN,2.9,40.8,NaN
15,108,서울,2025-01-16,-0.5,0.0,2.0,65.1,NaN
16,108,서울,2025-01-17,-0.5,NaN,1.8,62.4,NaN
17,108,서울,2025-01-18,1.0,NaN,1.6,54.1,NaN
18,108,서울,2025-01-19,3.8,NaN,1.8,65.0,NaN
19,108,서울,2025-01-20,3.9,0.0,1.7,73.1,NaN
20,108,서울,2025-01-21,2.4,NaN,1.6,79.8,NaN
21,108,서울,2025-01-22,3.6,NaN,1.9,70.3,NaN
22,108,서울,2025-01-23,2.0,NaN,1.6,54.3,NaN
23,108,서울,2025-01-24,3.1,NaN,1.5,45.9,NaN
24,108,서울,2025-01-25,5.2,NaN,3.1,52.8,NaN
25,108,서울,2025-01-26,4.6,NaN,2.8,50.5,NaN
26,108,서울,2025-01-27,0.2,5.6,3.5,77.9,2.6
27,108,서울,2025-01-28,-3.9,0.1,4.0,71.3,2.8
28,108,서울,2025-01-29,-4.6,0.2,3.1,66.1,2.9
29,108,서울,2025-01-30,-3.8,NaN,1.6,46.6,0.4
30,108,서울,2025-01-31,-0.8,2.4,2.1,80.1,2.9

In [16]:
df_wd.shape

(31, 8)